name: linux
on:
  push:
    branches: [ master ]
#  schedule:
#     - cron:  '0 8 * * *' # schedule 8:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./master
      - name: Checkout target
        uses: actions/checkout@v4
        with:
          ref: "linux"
          path: ./target
      - name: Build
        run: |
          cd ./master
          ./batch.sh ../target
