# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]
  schedule:
     - cron:  '0 8 * * *' # schedule 8:00

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - macos-11
          #- ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./master
      - name: Build
        run: |
          cd ./master
          ./batch.sh
      - name: Checkout branch mac
        uses: actions/checkout@v4
        with:
          ref: "macos"
          path: ./macos
      - name: Push to branch
        run: |
          cd ./macos
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rm -rf --ignore-unmatch .  > /dev/null
          cp -RfL ../master/dist/* .
          git add -f .
          git commit -m "Auto Build $(date +'%Y-%m-%d')"
          git push

